# Simple workflow for testing whether library builds
name: Test whether project builds

on:
  # Runs on pull requests targeting the default branch
  pull_request:
    types:
      - opened
      - edited
      - reopened
    branches:
      - 'main'
  push:
    branches-ignore:
      - 'main'
      

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Single deploy job since we're just deploying
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install library dependencies
        run: npm install
      - name: Build lib
        run: npm run build:lib
      - name: Install demo dependencies
        run: npm run install:demo
      - name: Build demo
        run: npm run build